### ISSUE TITLE
Incompatibility with PolyJuMP

### ISSUE THREAD

**Issue by tweisser** [tweisser/PolyModels#1]
While the package is basically doing what it should, see examples/breaking.jl, it breaks horribly, when used in combination with PolyJuMP. This is because both packages extend 
```
JuMP.build_constraint(::Function, ::AbstractPolynomialLike, : :MOI.AbstractScalarSet)
```
which is blind regarding the JuMP model. However, this function has to be defined, in order to be able to use the JuMP syntax.

**Comment by blegat** [comment]
We can catch the constraint in `add_constraint(::PolyModel, coefs, set::PolyJuMP.ZeroPolynomialSet)` and you can reconstruct the polynomial with `polynomial(coefs, set.monomials)`.
